[package]
name = "server"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies] 
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
mongodb = "2.2.0"
serde = "1.0.136"
serde_json = "1.0"
futures = "0.3"
okapi = { version = "0.6.0-alpha-1" }
rocket_okapi = { version = "0.8.0-rc.1", features = ["swagger", "secrets"] }
schemars = "0.8"