[package]
name = "poolnhl_interface"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
tokio = "1.38"
serde_json = "1.0"
rand = "0.8"
