[package]
name = "poolnhl_interface"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.80"
axum = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }
chrono = "0.4.38"
tokio = "1.38.0"
serde_json = "1.0.117"
rand = "0.8.5"
