[package]
name = "poolnhl_interface"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.68"
axum = "0.6.18"
serde = { version = "1.0.164", features = ["derive"] }
chrono = "0.4.26"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }

