[package]
name = "poolnhl_app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
poolnhl_infrastructure = { path = "../poolnhl_infrastructure" }
poolnhl_routing = { path = "../poolnhl_routing" }
tokio = "1.38.0"
tracing = "0.1.37"
