[package]
name = "poolnhl_routing"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6.18", features = ["macros"] }
poolnhl_interface = { path = "../poolnhl_interface" }
poolnhl_infrastructure = { path = "../poolnhl_infrastructure" }

tokio = "1.29.1"
tower-http = {version="0.4.1", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"